ProjectFirms01/Controllers/DocumentController.cs
using BusinessLayer.MdlClasses;
using BusinessLayer.MngClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectFirms01.Controllers
{
    public class DocumentController : Controller
    {
        // GET: Document
        public readonly MdlUserLogin sig = UtilityClass.GetUserSession(UtilityClass.UserSession.UserSessions);
        public ActionResult Index()
        {
             if (sig != null)
            {
            MngDocument mobj = new MngDocument();            
            return View(mobj.GetAllDocuments());
            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }
        }

        // GET: Document/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Document/Create
        public ActionResult Create()
        {  if (sig != null)
            {
            MdlDocument obj = new MdlDocument();
            return View(obj);
            }
        else
        {
            return RedirectToAction("Index", "Login");
        }
        }

        // POST: Document/Create
        [HttpPost]
        public ActionResult Create(MdlDocument obj)
        {
            if (sig != null)
            {
                try
                {
                    // TODO: Add insert logic here                
                    MngDocument mobj = new MngDocument();
                    mobj.AddNewDocument(obj);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: Document/Edit/5
        public ActionResult Edit(int id)
        {
              if (sig != null)
            {
            MngDocument mobj = new MngDocument();
             MdlDocument obj=new MdlDocument();
           obj= mobj.EditDocument(id);
            
            return View(obj);
            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        // POST: Document/Edit/5
        [HttpPost]
        public ActionResult Edit(MdlDocument obj)
        {
              if (sig != null)
            {
            try
            {
                // TODO: Add update logic here
                MngDocument mobj = new MngDocument();
                mobj.UpdateDocument(obj);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        // GET: Document/Delete/5
        public ActionResult Delete(int id)
        {
              if (sig != null)
            {
            MngDocument mobj = new MngDocument();
            MdlDocument obj = new MdlDocument();
            obj = mobj.EditDocument(id);

            return View(obj);
            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        // POST: Document/Delete/5
        [HttpPost]
        public ActionResult Delete(MdlDocument obj)
        {
             if (sig != null)
            {
            try
            {

                // TODO: Add delete logic here

                MngDocument mobj = new MngDocument();
              //  int id = obj.DocumentID;
                mobj.DelteDocType(obj.DocumentID);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }
        }
    }
}

ProjectFirms01/Controllers/OrgTypeController.cs
using BusinessLayer.MdlClasses;
using BusinessLayer.MngClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectFirms01.Controllers
{
    
    public class OrgTypeController : Controller
    {
        MngOrgType MngOrgTypeobj = new MngOrgType();
        // GET: OrgTyep
        public readonly MdlUserLogin sig = UtilityClass.GetUserSession(UtilityClass.UserSession.UserSessions);

        public ActionResult Index()
        {
             if (sig != null)
            {
            List<MdlOrgType> listorgtypes = new List<MdlOrgType>();
            listorgtypes = MngOrgTypeobj.GetAllOrgTypes();

            return View(listorgtypes);
            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }
        }

        public ActionResult Create()
        {
             if (sig != null)
            {
            MdlOrgType model = new MdlOrgType();
            return View(model);
            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }

        }
        [HttpPost]
        public ActionResult Create(MdlOrgType obj)
        { if (sig != null)
            {
            //MdlOrgType model = new MdlOrgType();
           // MngOrgType bznsorgtype = new MngOrgType();
                obj.EnteredByUser_ID = sig.UserID;
            MngOrgTypeobj.AddNewOrgType(obj);
            return RedirectToAction("Index");
            }
        else
        {
            return RedirectToAction("Index", "Login");
        }

        }
        public ActionResult Edit(int id)
        {
            if (sig != null)
            {
            MdlOrgType model = new MdlOrgType();

          model=MngOrgTypeobj.EditOrgType(id);
            return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }
        [HttpPost]
        public ActionResult Edit(MdlOrgType obj)
        { 
             if (sig != null)
            {
                obj.EnteredByUser_ID = sig.UserID;
            MngOrgTypeobj.UpdateOrgType(obj);
            return RedirectToAction("Index");
            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }

        }
    }
}

ProjectFirms01/Views/Shared/_FirmLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Firm</title>
    <link href="~/Content/AdminLTE/css/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    
    <link href="@Url.Content("~/Content/kendo/kendo.flat.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/kendo/kendo.common.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/toastr.css")" rel="stylesheet" />


    <link href="~/Content/AdminLTE/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE/css/ionicons.min.css" rel="stylesheet" />


 


    @*<link href="~/Content/AdminLTE/css/datatables/dataTables.bootstrap.css" rel="stylesheet" />*@
    <link href="~/Content/AdminLTE/css/morris/morris.css" rel="stylesheet" />
 

    <link href="~/Content/AdminLTE/css/AdminLTE.css" rel="stylesheet" />

 
    <link href="~/Content/toastr.css" rel="stylesheet" />

    @*<link href="~/Content/kendo/bootstrap.min.css" rel="stylesheet" />*@
    <link href="~/Content/kendo/dataTables.bootstrap.min.css" rel="stylesheet" />



    @*<script type="text/javascript" language="javascript" src="//code.jquery.com/jquery-1.12.4.js"></script>*@
    @*<script src="~/Scripts/Kendo/jquery-2.0.3.min.js" type="text/javascript"></script>*@
    <script type="text/javascript" language="javascript" src="~/Scripts/jquery-1.12.4.js"></script>

   
        <script src="@Url.Content("~/Scripts/Kendo/kendo.all.min.js")"></script>

    <script src="~/Scripts/jquery.maskinput.js"></script>
    <link href="~/Content/dd.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.dd.js"></script>
    <style>
        .errorClass {
            border: 2px solid red;
        }
           .dd .ddArrow {
            background-image: url(../images/ESSarrow.png);
        }

            .row .col-sm-12
        {
            overflow-x:scroll !important;
        }
    </style>


    @* This is for kendo date picker
        
        
        <script>
       
    $(document).ready(function () {
    $('input[type="date"]').kendoDatePicker({
    value: new Date(),
    min: new Date(new Date() - 1),
    height:22,
    //format: "yyyy-MM-dd  h:mm:ss tt"
    format: "yyyy-MM-dd"
    });

    $('input[type="date"]').attr('readonly', true);
    });
    </script>*@
</head>
<body class="skin-blue" style="overflow-x:visible !important">
    <div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px; top: 0px; width: 100%; height: 100%; background-color: rgb(102, 102, 102); z-index: 30001; opacity: 0.8;display:none;">
        <p style="position: absolute; color: White; top: 45%; left: 45%;">
            <img src="~/images/loading-image.gif" style="width:50px; height:50px;" />
        </p>
    </div>

    <div class="col-md-12">
    
     

        <div class="col-md-3">
            @RenderSection("Sidebar", false)
        </div>
    
        <div class="col-md-8" style="width:83%;float: right;">
            @RenderSection("Header", false)
            @RenderSection("BodyContent", false)


        </div>
            @RenderSection("FooterArea", false)
        </div><!-- ./wrapper -->
       
    
    <div class="modal fade" id="myModal" role="dialog" data-backdrop="static" data-keyboard="false">
        <div id="ModelContentArea">
            
        </div>
    </div>

     
  
      @*<script src="~/Content/AdminLTE/js/plugins/datatables/dataTables.bootstrap.js"></script>
      <script src="~/Content/AdminLTE/js/plugins/datatables/jquery.dataTables.js"></script>*@
    <script src="~/Scripts/bootstrap.js"></script>

    <script type="text/javascript" language="javascript" src="~/Scripts/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="~/Scripts/dataTables.bootstrap.min.js"></script>
    @*<script type="text/javascript" language="javascript" src="~/Scripts/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" language="javascript" src="~/Scripts/jquery.dataTables.min.js"></script>*@


     <script src="~/plugins/jquery.slimscroll.min.js"></script>
    <script src="~/plugins/fastclick.js"></script>
        @*<script src="~/Scripts/respond.js"></script>*@

       @*<script src="~/Content/AdminLTE/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>*@
        @*<script src="~/Content/AdminLTE/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>*@
        @*<script src="~/Content/AdminLTE/js/plugins/morris/morris.min.js"></script>*@
        @*<script src="~/Content/AdminLTE/js/plugins/sparkline/jquery.sparkline.min.js"></script>*@
        @*<script src="~/Content/AdminLTE/js/plugins/fullcalendar/fullcalendar.min.js"></script>*@

        @*<script src="~/Content/AdminLTE/js/plugins/jqueryKnob/jquery.knob.js"></script>*@
        @*<script src="~/Content/AdminLTE/js/plugins/daterangepicker/daterangepicker.js"></script>*@
        @*<script src="~/Content/AdminLTE/js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>*@
        @*<script src="~/Content/AdminLTE/js/plugins/iCheck/icheck.min.js"></script>*@
        <script src="~/Content/AdminLTE/js/AdminLTE/app.js"></script> 
    <script src="@Url.Content("~/Scripts/toastr.js")"></script>

   
    <script>

        //$(document).ready(function () {
        //    $('#example1').DataTable({
        //        "scrollY": "200px",
        //        "scrollCollapse": true,
        //        "paging": false
        //    });
        //});
    $(function () {
        $("#example1").DataTable();
        //$('#example2').DataTable({
        //    "paging": true,
        //    "lengthChange": false,
        //    "searching": false,
        //    "ordering": true,
        //    "info": true,
        //    "autoWidth": false
        //});
    });
    </script>
    <script type="text/javascript">
    $(document).ready(function () {
        $(".loader").bind("window", (function () {
            $("#divLoading").show();
        }));
    });
    </script>

      
</body>
</html>

ProjectFirms01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Firm", "Index", "Firm", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Firm", "Index", "Firm")</li>
                    <li>@Html.ActionLink("Business Type", "Index", "BusinessType")</li>
                    <li>@Html.ActionLink("Org Type", "Index", "OrgType")</li>
                    <li>@Html.ActionLink("Addresss", "Index", "Addresss")</li>
                    <li>@Html.ActionLink("Partner", "Index", "Partner")</li>
                    <li>@Html.ActionLink("Witness", "Index", "Witness")</li>
                    <li>@Html.ActionLink("Document Type", "Index", "Document")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>