ProjectFirms01/Controllers/PartnerController.cs
using BusinessLayer.MdlClasses;
using BusinessLayer.MngClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectFirms01.Controllers
{
    public class PartnerController : Controller
    {
        // GET: Partner
        MdlPartner obj = new MdlPartner();
        MngPartner mobj = new MngPartner();
        List<MdlPartner> Lobj = new List<MdlPartner>();
        MngADDRESSS MobjAddress = new MngADDRESSS();
        public readonly MdlUserLogin sig = UtilityClass.GetUserSession(UtilityClass.UserSession.UserSessions);
        public ActionResult Index()
        {
             if (sig != null)
            {
            Lobj = mobj.GetAllPartnerList();
            return View(Lobj);
            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }
        }

        // GET: Partner/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Partner/Create
        public ActionResult Create(string Flag)
        {
              if (sig != null)
            {
            if (Flag == "SideBar")
            {
                UtilityClass.NullSession(UtilityClass.UserSession.OrgDocId, null);
            }
           
            obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocId(0);
         //   obj.Designation = mobj.GetAllDesignation();
            return View(obj);
            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        // POST: Partner/Create
        [HttpPost]
        public ActionResult Create(MdlPartner obj)
        {
              if (sig != null)
            {
            try
            {
                // TODO: Add insert logic here
                obj.EnterByUser_ID =sig.UserID;
                mobj.AddNewPartner(obj);

                return RedirectToAction("Index");
            }
            catch
            {
                obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocId(0);
                return View(obj);
            }
            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }



        [HttpPost]
        public ActionResult SetShare(long PartnerID, int PartnerShare)
        {
            var sig = UtilityClass.GetUserSession(UtilityClass.UserSession.UserSessions);
            var Orgdoc = UtilityClass.GetOrgDocIdSession(UtilityClass.UserSession.OrgDocId);

            if (sig != null)
            {

                string message = string.Empty, status = string.Empty;
                try
                {
                    MdlPartner Pmodel = new MdlPartner();
                    MngPartner mobj = new MngPartner();
                    Pmodel.EnterByUser_ID = sig.UserID;
                    Pmodel.OrgDoc_ID = Convert.ToInt64(Orgdoc.OrgDocID.ToString());
                    Pmodel.PartnerID = PartnerID;
                    Pmodel.PartnerShare = PartnerShare;
                     mobj.SetPartnerShare(Pmodel);

                    
                    message = BusinessLayer.MdlClasses.UtilityClass.UtilityMessages.updatemessage.ToString();
                    status = BusinessLayer.MdlClasses.UtilityClass.Enums.ErrorClass.success.ToString();
                }
                catch (Exception ex)
                {
                    message = BusinessLayer.MdlClasses.UtilityClass.UtilityMessages.errormessage.ToString();
                    status = BusinessLayer.MdlClasses.UtilityClass.Enums.ErrorClass.error.ToString();
                }

                return Json(new { status = status.ToString(), message = message.ToString() });

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }


        [HttpPost]
        public ActionResult NewFormHIssue(string NewFormHIssueNo, DateTime NewFormHIssueDate)
        {
            var sig = UtilityClass.GetUserSession(UtilityClass.UserSession.UserSessions);
            var Orgdoc = UtilityClass.GetOrgDocIdSession(UtilityClass.UserSession.OrgDocId);

            if (sig != null)
            {

                string message = string.Empty, status = string.Empty;
                try
                {
                    MdlPartner Pmodel = new MdlPartner();
                    MngPartner mobj = new MngPartner();
                    Pmodel.EnterByUser_ID = sig.UserID;
                    Pmodel.OrgDoc_ID = Convert.ToInt64(Orgdoc.OrgDocID.ToString());
                    Pmodel.NewFormHIssueNo = NewFormHIssueNo;
                    Pmodel.NewFormHIssueDate = NewFormHIssueDate;
                    mobj.NewFormHIssue(Pmodel);
                    SignOut();
                   
                    message = BusinessLayer.MdlClasses.UtilityClass.UtilityMessages.updatemessage.ToString();
                    status = BusinessLayer.MdlClasses.UtilityClass.Enums.ErrorClass.success.ToString();
                }
                catch (Exception ex)
                {
                    message = ex.Message;// BusinessLayer.MdlClasses.UtilityClass.UtilityMessages.errormessage.ToString();
                    status = BusinessLayer.MdlClasses.UtilityClass.Enums.ErrorClass.error.ToString();
                }

                return Json(new { status = status.ToString(), message = message.ToString() });

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }


        public void SignOut()
        {
           
            UtilityClass.NullSession(UtilityClass.UserSession.OrgDocId, null);
             
        }
        public ActionResult FormEPartner(string Flag)
        {
              if (sig != null)
            {
            if (Flag == "SideBar")
            {
                UtilityClass.NullSession(UtilityClass.UserSession.OrgDocId, null);
            }

            obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocId(0);
            //   obj.Designation = mobj.GetAllDesignation();
            return View(obj);
            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        public ActionResult NewFormEPartner(string Flag)
        {
            if (sig != null)
            {
                if (Flag == "SideBar")
                {
                    UtilityClass.NullSession(UtilityClass.UserSession.OrgDocId, null);
                }

                obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocId(0);
                //   obj.Designation = mobj.GetAllDesignation();
                return View(obj);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpPost]
        public ActionResult NewFormEPartner(MdlPartner obj)
        {

            if (sig != null)
            {
                try
                {
                    // TODO: Add insert logic here
                    obj.EnterByUser_ID = sig.UserID;
                    mobj.AddNewPartner(obj);

                    return RedirectToAction("NewFormEIndex");
                }
                catch(Exception ex)
                {
                    obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocId(0);

                    return View(obj);
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: Partner/Edit/5
        public ActionResult NewFormEEdit(long id)
        {
            if (sig != null)
            {
                obj = mobj.GetPartnerDataForEdit(id);
                obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocId(obj.OrgDoc_ID);
                return View(obj);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: Partner/Edit/5
        [HttpPost]
        public ActionResult NewFormEEdit(MdlPartner Pmodel)
        {
            if (sig != null)
            {
                try
                {
                    // TODO: Add update logic here
                    Pmodel.EnterByUser_ID = sig.UserID;
                    mobj.UpdatePartner(Pmodel);
                    return RedirectToAction("NewFormEIndex");
                }
                catch
                {
                    obj = mobj.GetPartnerDataForEdit(0);
                    obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocId(obj.OrgDoc_ID);
                    return View(obj);
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        [HttpPost]
        public ActionResult FormEPartner(MdlPartner obj)
        {
            
              if (sig != null)
            {
            try
            {
                // TODO: Add insert logic here
                obj.EnterByUser_ID = sig.UserID;
                mobj.AddNewPartner(obj);

                return RedirectToAction("FormEIndex");
            }
            catch
            {
                obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocId(0);
                 
                return View(obj);
            }
            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }



        public ActionResult FormEIndex()
        {
            var sig1 = UtilityClass.GetOrgDocIdSession(UtilityClass.UserSession.OrgDocId);
            long ID;
            if (sig != null)
            {
                //it will return the list during insert new partner throgh form H
                ID = Convert.ToInt32(sig1.OrgDocID.ToString());
                Lobj = mobj.GetAllFormEPartnerList(ID);
                return View(Lobj);
            }
            else
            {

ProjectFirms01/Views/Firm/FormE.cshtml
@model BusinessLayer.MdlClasses.MdlPartner

@{
    ViewBag.Title = "Form E";
    Layout = "~/Views/Shared/_FirmLayout.cshtml";
}

<h2>FormE</h2>
@section Header{
    @Html.Partial("~/Views/Shared/PartialViews/_Header.cshtml")
}

@section Sidebar{
    @Html.Partial("~/Views/Shared/PartialViews/_SideBar.cshtml")
}


@section BodyContent{ 
    <style> 
        .form-control{
            width:400px;
        } 
    </style>
  @{
      var sig = BusinessLayer.MdlClasses.UtilityClass.GetOrgIdSessionPartner(BusinessLayer.MdlClasses.UtilityClass.UserSession.OrgIdforpartner); 
   }

@if (sig != null)
{
<div style="float:right;margin-right:100px;">

    <input type="button" id="UndoDeActivePartner" value="Undo deactivate Partner" class="btn btn-default" />

    <input type="hidden" id="OrgDoc_ID" name="OrgDoc_ID" value="@sig.OrgDoc_ID" />
    </div> 
}
else
{
   <div style="float:right;margin-right:100px;">

       <input type="button" id="DeActivePartner" value="Deactivate Partner" class="btn btn-default" />



</div> 
}

<h2>Form E</h2>



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-sm-6">

                    <label class="control-label ">Organization/File#</label>
                    <div>
                        <select class="form-control OrgId" name="OrgId" id="OrgId" style="background:#fff">

                            <option value="0">--Select Organization/File #--</option>

                            @foreach (var item in @Model.GetAllOrgId)
                            {
                                <option selected="@item.Selected" value="@item.Value">@item.Label - @item.OptionalLabel</option>
                            }
                        </select>

                    </div>

                </div>
                <div class="col-sm-6">
                    <label class="control-label ">New Form H Issue No</label>
                    <div>
                        <input type="text" id="NewFormHIssueNo" name="NewFormHIssueNo" class="form-control" />
                               @Html.ValidationMessageFor(model => model.NewFormHIssueNo, "", new { @class = "text-danger" })
                    </div>


                </div>
            </div>

            <div class="row">

                <div class="col-sm-6">

                    <label class="control-label">Form E Submission Date</label>
                    <div>
                        <input type="date" id="FormESubmissionDate" name="FormESubmissionDate" class="form-control" />
                        @Html.ValidationMessageFor(model => model.FormESubmissionDate, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="col-sm-6">

                    <label class="control-label">New Form H Issue Date</label>
                    <div>

                        <input type="date" id="NewFormHIssueDate" name="NewFormHIssueDate" class="form-control" />

                        @Html.ValidationMessageFor(model => model.NewFormHIssueDate, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>

            

             

            <div class="row">
                <div class="col-sm-6">

                    <div style="margin-top:10px">
                        <input type="submit" id="InsertFirmNewFormEDetail" value="Save" class="btn btn-default" />
                    </div>

                </div>
 

            </div>
        </div>

    }




<div class="modal fade" id="Close_ProjectModal" role="dialog" tabindex="-1" aria-labelledby="purchaseLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" style="width: 40%; margin-top: 9% !important;">

        <div class="modal-content">
            <div class="modal-header" style="background-color:#363940;height:38px;padding:0px">
                <h4 class="modal-title" style="text-align:center; color:white">Alert</h4>
            </div>
            <div class="modal-body">
                <b>Are you sure to deactivate current partner?</b>
            </div>
            <div class="modal-footer" style="height:48px;padding:6px 23px 0 0">
                <button type="button" id="btnConform" style="height:35px;width:80px;font-size:12px" class="k-button hide-on-narrow">Yes</button>
                <button type="button" id="btnCancalConform"  style="height:35px;width:80px;font-size:12px" class="btn btn-danger">No</button>
            </div>
        </div>
    </div>

</div>

    <script>


        $('#NewFormHIssueNo').focusin(function () {
            $('#NewFormHIssueNo').mask("999999");
        });
        $('#btnCancalConform').click(function () {
              $('#Close_ProjectModal').modal("hide")
             $('#myModal').modal("show"); 
        });

        $('#UndoDeActivePartner').click(function () { 
            var OrgDoc_ID = $('#OrgDoc_ID').val();
          
           // alert(OrgDoc_ID);
            $.ajax({
                url: '/Firm/UndoDeActivePartner',
                type: 'POST',
                data: { ID: OrgDoc_ID },
                success: function (data) {
                    location.reload();
                    toastr.success(data.message);
                   
                    // alert(data.name);
                },
                error: function (data) {
                   
                    toastr.error(data.message);
                    //  alert("error");
                }
            });
            return false;         

        });

        $('#btnConform').click(function () {
           
            //$('#myModal').modal({ show: true });
            //$('#Close_ProjectModal').modal({ hide: true });
            //$("#issueCancel").trigger("click"); 
            var OrgDoc_ID = $('#OrgDoc_ID option:selected').val();
           // alert(OrgDoc_ID);
           
                $.ajax({
                    url: '/Firm/DeactivatePartner',
                    type: 'POST',
                    data: {ID: OrgDoc_ID},
                    success: function (data) {
                        $('#Close_ProjectModal').modal("hide");
                        toastr.success(data.message);
                        location.reload();
                       // alert(data.name);
                    },
                    error: function (data) {
                        $('#myModal').modal("show");
                       toastr.error(data.message);
                      //  alert("error");
                    }
                });
                return false;
          
            //$.ajax({
            //    url: "/Firm/DeactivatePartner",
            //    //type: "POST",
            //    data: {ID: OrgDoc_ID},
            //    dataType: "json",
            //    traditional: true,
            //    contentType: "application/json; charset=utf-8",
            //    type: 'POST',
            //    //async: false,
            //    //dataType: 'json',

            //    //contentType: false,
            //    //processData: false,
            //    success: function (data) {
            //        $('#Close_ProjectModal').modal("hide")
            //        toastr.success(data.message); 

            //    },
            //    error: function (data) {
            //        $('#myModal').modal("show");
            //        toastr.error(data.message);
            //    }
            //});
           
        });


        $("#DeActivePartner").click(function () {
            
          //  $('#myModal').modal({ show: true });
            $.ajax({
                url: '/Firm/DeactivatePartner',
                type: 'GET',
                success: function (data) {                  
                    $('#myModal').modal({ show: true });
                    $("#ModelContentArea").html("").append(data);
                },
                error: function () {
                    //  toastr.error(data.message);
                }
            });
        });

        $(document).ready(function () {
            $(".OrgId").msDropDown();
        });

        //  $(document).ready(function () {
        // alert("hi");
      

     
 
    </script>

    <div>
        @Html.ActionLink("Back to List", "FormEIndex","Partner")
    </div>
}




@section FooterArea{
    @Html.Partial("~/Views/Shared/PartialViews/_Footer.cshtml")


}

ProjectFirms01/Views/Firm/NewFormE.cshtml
@{
    ViewBag.Title = "NewFormE";
    Layout = "~/Views/Shared/_FirmLayout.cshtml";
}

 
@model BusinessLayer.MdlClasses.MdlPartner

@{
    ViewBag.Title = "Form E";
    Layout = "~/Views/Shared/_FirmLayout.cshtml";
}

<h2>FormE</h2>
@section Header{
    @Html.Partial("~/Views/Shared/PartialViews/_Header.cshtml")
}

@section Sidebar{
    @Html.Partial("~/Views/Shared/PartialViews/_SideBar.cshtml")
}


@section BodyContent{
    <style>
        .form-control {
            width: 400px;
        }
    </style>
    @*@{
        var sig = BusinessLayer.MdlClasses.UtilityClass.GetOrgIdSessionPartner(BusinessLayer.MdlClasses.UtilityClass.UserSession.OrgIdforpartner);
    }

    @if (sig != null)
    {
        <div style="float:right;margin-right:100px;">

            <input type="button" id="UndoDeActivePartner" value="Undo deactivate Partner" class="btn btn-default" />

            <input type="hidden" id="OrgDoc_ID" name="OrgDoc_ID" value="@sig.OrgDoc_ID" />
        </div>
    }
    else
    {
        <div style="float:right;margin-right:100px;">
            <input type="button" id="DeActivePartner" value="Deactivate Partner" class="btn btn-default" />
        </div>
    }*@

    <h2>New Form E</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-sm-6">

                    <label class="control-label ">Organization/File#</label>
                    <div>
                        <select class="form-control OrgId" name="OrgId" id="OrgId" style="background:#fff">

                            <option value="0">--Select Organization/File #--</option>

                            @foreach (var item in @Model.GetAllOrgId)
                            {
                                <option selected="@item.Selected" value="@item.Value">@item.Label - @item.OptionalLabel</option>
                            }
                        </select>

                    </div>
                    <input type="hidden" id="OrgName" name="OrgName" value="" />
                </div>
                <div class="col-sm-6">
                    @*<label class="control-label ">New Form H Issue No</label>
                    <div>
                        <input type="text" id="NewFormHIssueNo" name="NewFormHIssueNo" class="form-control" />
                        @Html.ValidationMessageFor(model => model.NewFormHIssueNo, "", new { @class = "text-danger" })
                    </div>*@


                </div>
            </div>

            <div class="row">

                <div class="col-sm-6">

                    <label class="control-label">Form E Submission Date</label>
                    <div>
                        <input type="date" id="FormESubmissionDate" name="FormESubmissionDate" class="form-control" />
                       
                    </div>

                </div>
                <div class="col-sm-6">

                    @*<label class="control-label">New Form H Issue Date</label>
                    <div>

                        <input type="date" id="NewFormHIssueDate" name="NewFormHIssueDate" class="form-control" />

                       
                    </div>*@

                </div>
            </div>





            <div class="row">
                <div class="col-sm-6">

                    <div style="margin-top:10px">
                        <input type="submit" id="InsertNewFirmNewFormEDetail" value="Save" class="btn btn-default" />
                    </div>

                </div>


            </div>
        </div>

    }




    <div class="modal fade" id="Close_ProjectModal" role="dialog" tabindex="-1" aria-labelledby="purchaseLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog" style="width: 40%; margin-top: 9% !important;">

            <div class="modal-content">
                <div class="modal-header" style="background-color:#363940;height:38px;padding:0px">
                    <h4 class="modal-title" style="text-align:center; color:white">Alert</h4>
                </div>
                <div class="modal-body">
                    <b>Are you sure to deactivate current partner?</b>
                </div>
                <div class="modal-footer" style="height:48px;padding:6px 23px 0 0">
                    <button type="button" id="btnConform" style="height:35px;width:80px;font-size:12px" class="k-button hide-on-narrow">Yes</button>
                    <button type="button" id="btnCancalConform" style="height:35px;width:80px;font-size:12px" class="btn btn-danger">No</button>
                </div>
            </div>
        </div>

    </div>

    <script>

        $('#InsertNewFirmNewFormEDetail').click(function () {
            var OrgName = $('#OrgId option:selected').text();
            $('#OrgName').val(OrgName);


        });


        $('#NewFormHIssueNo').focusin(function () {
            $('#NewFormHIssueNo').mask("999999");
        });
        $('#btnCancalConform').click(function () {
              $('#Close_ProjectModal').modal("hide")
             $('#myModal').modal("show");
        });

        $('#UndoDeActivePartner').click(function () {
            var OrgDoc_ID = $('#OrgDoc_ID').val();

           // alert(OrgDoc_ID);
            $.ajax({
                url: '/Firm/UndoDeActivePartner',
                type: 'POST',
                data: { ID: OrgDoc_ID },
                success: function (data) {
                    location.reload();
                    toastr.success(data.message);

                    // alert(data.name);
                },
                error: function (data) {

                    toastr.error(data.message);
                    //  alert("error");
                }
            });
            return false;

        });

        $('#btnConform').click(function () {

            //$('#myModal').modal({ show: true });
            //$('#Close_ProjectModal').modal({ hide: true });
            //$("#issueCancel").trigger("click");
            var OrgDoc_ID = $('#OrgDoc_ID option:selected').val();
           // alert(OrgDoc_ID);

                $.ajax({
                    url: '/Firm/DeactivatePartner',
                    type: 'POST',
                    data: {ID: OrgDoc_ID},
                    success: function (data) {
                        $('#Close_ProjectModal').modal("hide");
                        toastr.success(data.message);
                        location.reload();
                       // alert(data.name);
                    },
                    error: function (data) {
                        $('#myModal').modal("show");
                       toastr.error(data.message);
                      //  alert("error");
                    }
                });
                return false;

            //$.ajax({
            //    url: "/Firm/DeactivatePartner",
            //    //type: "POST",
            //    data: {ID: OrgDoc_ID},
            //    dataType: "json",
            //    traditional: true,
            //    contentType: "application/json; charset=utf-8",
            //    type: 'POST',
            //    //async: false,
            //    //dataType: 'json',

            //    //contentType: false,
            //    //processData: false,
            //    success: function (data) {
            //        $('#Close_ProjectModal').modal("hide")
            //        toastr.success(data.message);

            //    },
            //    error: function (data) {
            //        $('#myModal').modal("show");
            //        toastr.error(data.message);
            //    }
            //});

        });


        $("#DeActivePartner").click(function () {

          //  $('#myModal').modal({ show: true });
            $.ajax({
                url: '/Firm/DeactivatePartner',
                type: 'GET',
                success: function (data) {
                    $('#myModal').modal({ show: true });
                    $("#ModelContentArea").html("").append(data);
                },
                error: function () {
                    //  toastr.error(data.message);
                }
            });
        });

        $(document).ready(function () {
            $(".OrgId").msDropDown();
        });

        //  $(document).ready(function () {
        // alert("hi");




    </script>

    <div>
        @Html.ActionLink("Back to List", "FormEIndex", "Partner")
    </div>
}




@section FooterArea{
    @Html.Partial("~/Views/Shared/PartialViews/_Footer.cshtml")


}