ProjectFirms01/Controllers/AddresssController.cs
using BusinessLayer.MdlClasses;
using BusinessLayer.MngClasses;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ProjectFirms01.Controllers
{
   

    public class AddresssController : Controller
    {
        // GET: Addresss
        MdlADDRESSS obj = new MdlADDRESSS();
        MngADDRESSS mobj = new MngADDRESSS();
        List<MdlADDRESSS> objList = new List<MdlADDRESSS>();
        public readonly MdlUserLogin sig = UtilityClass.GetUserSession(UtilityClass.UserSession.UserSessions);
        public ActionResult Index()
        {
             if (sig != null)
            {
            objList = mobj.GetAllAddress(1);
            return View(objList);

            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }
        }

 
      

        // GET: Addresss/Create
        public ActionResult Create(string Flag)
        {
              if (sig != null)
            {
            if (Flag == "SideBar")
            {
             UtilityClass.NullSession(UtilityClass.UserSession.OrgDocId, null);
            }
            //else
            //{
            //   UtilityClass.AddSession(UtilityClass.UserSession.OrgDocId,"10023");
            //}
            obj.DistricsDDL = mobj.GetAllDistrics(0);
            obj.AddressTypes = mobj.GetAllAddressType(0);
            obj.GetAllOrgDocId = mobj.GetAllOrgDocId(0);         
            return View(obj);

            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }


     
        //For testing dropdown change and fill through dataset for now not in use 
        public JsonResult GetTehsils1(int ID)
        {

           var list  = new List<Dropdownlist>();            
           var ds = mobj.GetTehsilsByDistricbyDataset(ID);
           
           foreach (DataRow dr in ds.Tables[0].Rows)
           {
               list.Add(new Dropdownlist
               {
                   Label = dr["Label"].ToString(),
                   Value =Convert.ToInt16(dr["Value"].ToString())
               });
           }
            return Json(list, JsonRequestBehavior.AllowGet);
        }


       // [HttpPost]
        public JsonResult GetTehsils(int ID, int Tehsil)
        {
            List<Dropdownlist> list = new List<Dropdownlist>();
            list = mobj.GetTehsilsByDistric(ID,Tehsil);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        // POST: Addresss/Create
        [HttpPost]
        public ActionResult Create(MdlADDRESSS objform)
        {
            
              if (sig != null)
            {
            try
            {
                // TODO: Add insert logic here
                objform.EnterByUser_ID = sig.UserID;
                mobj.AddAddresss(objform);
                //TempData["foo1"] = "From Create";
                return RedirectToAction("Index");
            }
            catch
            {
                
                obj.DistricsDDL = mobj.GetAllDistrics(0);
                obj.AddressTypes = mobj.GetAllAddressType(0);
                obj.GetAllOrgDocId = mobj.GetAllOrgDocId(0);
                return View(obj);
               
            }

            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        // GET: Addresss/Edit/5
        public ActionResult Edit(int id)
        {  
            
              if (sig != null)
            {
            obj = mobj.EditADDRESSS(id);
            obj.DistricsDDL = mobj.GetAllDistrics(obj.Distric_ID);
            obj.AddressTypes = mobj.GetAllAddressType(obj.AdressType_ID);
            obj.GetAllOrgDocId = mobj.GetAllOrgDocId(obj.OrgDoc_ID);  
          
            return View(obj);

            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        // POST: Addresss/Edit/5
        [HttpPost]
        public ActionResult Edit(MdlADDRESSS objform)
        {
            
              if (sig != null)
            {
            try
            {
                // TODO: Add update logic here
                objform.ModifyByUser_ID = sig.UserID;
                mobj.UpdateAddress(objform);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }


            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }



     




        [HttpGet]
        public ActionResult ListOfAddress(long Id)
        {
            //List<MdlPartner> model = new List<MdlPartner>();
            var sig = UtilityClass.GetOrgDocIdSession(UtilityClass.UserSession.OrgDocId);
            long ID;
            if (sig != null)
            {
                ID = Convert.ToInt32(sig.OrgDocID.ToString());
                objList = mobj.OrgAddressList(ID);
            }
            else
            {
                ID = Id;
                objList = mobj.OrgAddressList(ID);
            }
            return PartialView("~/Views/Addresss/PartialViews/_OrgAddressList.cshtml", objList);
        }



      
        public ActionResult Details(int id)
        {
              
              if (sig != null)
            {
            obj = mobj.EditADDRESSS(id);
            return View(obj);

            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }
        // GET: Addresss/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Addresss/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }





        #region Address Alter
        public ActionResult AddressAlter()
        {
                
              if (sig != null)
            {
            obj.GetAllOrgDocId = mobj.GetAllOrgDocIdForAlterAddress(0);
            obj.DistricsDDL = mobj.GetAllDistrics(0);
            obj.AddressTypes = mobj.GetAllAddressType(0);         
            return View(obj);

            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        [HttpPost]
        public ActionResult AddressAlter(MdlADDRESSS objform)
        {
                 
              if (sig != null)
            {
            try
            {
                // TODO: Add insert logic here
                objform.EnterByUser_ID = sig.UserID;
                mobj.InsertFormBAlterAddress(objform);
                //TempData["foo1"] = "From Create";
                return RedirectToAction("Index");
            }
            catch
            {
                obj.GetAllOrgDocId = mobj.GetAllOrgDocIdForAlterAddress(0);
                obj.DistricsDDL = mobj.GetAllDistrics(0);
                obj.AddressTypes = mobj.GetAllAddressType(0);
                return View(obj);
                
            }

            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }


        [HttpGet]
        public ActionResult ListOfAddressAlter(long Id)
        {
            //List<MdlPartner> model = new List<MdlPartner>();
            var sig = UtilityClass.GetOrgDocIdSession(UtilityClass.UserSession.OrgDocId);
            long ID;
            if (sig != null)
            {
                ID = Convert.ToInt32(sig.OrgDocID.ToString());
                objList = mobj.OrgAddressAlterList(ID);
            }
            else
            {
                ID = Id;
                objList = mobj.OrgAddressAlterList(ID);
            }
            return PartialView("~/Views/Addresss/PartialViews/_OrgAddressForAlter.cshtml", objList);
        }







        #endregion



        #region Madrassa
        public ActionResult CreateMadrassaAddress(string Flag)
        {
             if (sig != null)
            {
            if (Flag == "SideBar")
            {
                UtilityClass.NullSession(UtilityClass.UserSession.OrgDocId, null);
            }
            
            obj.DistricsDDL = mobj.GetAllDistrics(0);
            obj.AddressTypes = mobj.GetAllAddressType(0);
            obj.GetAllOrgDocId = mobj.GetAllOrgDocIdForMadrassa(0);
            return View(obj);

            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }
        }


        [HttpPost]
        public ActionResult CreateMadrassaAddress(MdlADDRESSS objform)
        {
             if (sig != null)
            {
            try
            {
                // TODO: Add insert logic here
                objform.EnterByUser_ID = sig.UserID;
                mobj.AddAddresss(objform);
                //TempData["foo1"] = "From Create";
                return RedirectToAction("MadrassaAddresses");
            }
            catch
            {

                obj.DistricsDDL = mobj.GetAllDistrics(0);
                obj.AddressTypes = mobj.GetAllAddressType(0);
                obj.GetAllOrgDocId = mobj.GetAllOrgDocIdForMadrassaAlterAddress(0);
                return View(obj);

            }

            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }
        }



        public ActionResult UpdateMadrassaAddress(int id)
        {
             if (sig != null)
            {
            obj = mobj.EditADDRESSS(id);
            obj.DistricsDDL = mobj.GetAllDistrics(obj.Distric_ID);

ProjectFirms01/Controllers/WitnessController.cs
using BusinessLayer.MdlClasses;
using BusinessLayer.MngClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectFirms01.Controllers
{
    public class WitnessController : Controller
    {
        // GET: Witness
        MdlWitness obj = new MdlWitness();
        List<MdlWitness> Lobj = new List<MdlWitness>();
        MngWitness mobj = new MngWitness();
        MngADDRESSS MobjAddress = new MngADDRESSS();
        public readonly MdlUserLogin sig = UtilityClass.GetUserSession(UtilityClass.UserSession.UserSessions);
        public ActionResult Index()
        {
             if (sig != null)
            {
            Lobj = mobj.GetAllWitnessList();

            return View(Lobj);
            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }
        }

        // GET: Witness/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Witness/Create
        public ActionResult Create(string Flag)
        {
             if (sig != null)
            {
            if (Flag == "SideBar")
            {
                UtilityClass.NullSession(UtilityClass.UserSession.OrgDocId, null);
            }

            obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocId(0);
            return View(obj);
            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }
        }


        // POST: Witness/Create
        [HttpPost]
        public ActionResult Create(MdlWitness obj)
        {
              if (sig != null)
            {
            try
            {
                // TODO: Add insert logic here
                obj.EnterByUser_ID = sig.UserID;
                mobj.AddNewWitness(obj);
                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        // GET: Witness/Edit/5
        public ActionResult Edit(long id)
        {  if (sig != null)
            {
            obj = mobj.GetWitnessInfoForEdit(id);
            obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocId(obj.OrgDoc_ID);
            return View(obj);
             }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        // POST: Witness/Edit/5
        [HttpPost]
        public ActionResult Edit(MdlWitness Wmodel)
        {
            if (sig != null)
            {
            try
            {
                // TODO: Add update logic here
                Wmodel.EnterByUser_ID = sig.UserID;
                mobj.UpdateWitness(Wmodel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
             }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }

        // GET: Witness/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Witness/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        [HttpGet]
        public ActionResult ListOfWitness(long Id)
        {
            //List<MdlPartner> model = new List<MdlPartner>();

            var sig = UtilityClass.GetOrgDocIdSession(UtilityClass.UserSession.OrgDocId);
            long ID;
            if (sig != null)
            {
                ID = Convert.ToInt32(sig.OrgDocID.ToString());
                Lobj = mobj.OrgWitnessList(ID);
            }
            else
            {
                ID = Id;
                Lobj = mobj.OrgWitnessList(ID);
            }
            return PartialView("~/Views/Witness/PartialViews/_OrgWitnessList.cshtml", Lobj);
        }




        #region madrassa

        public ActionResult MadrassaWitnessList()
        {
            if (sig != null)
            {
            Lobj = mobj.GetAllWitnessListForMadrassa();

            return View(Lobj);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        // GET: Witness/Create
        public ActionResult CreateMadrassaWitness(string Flag)
        {
             if (sig != null)
            {
            if (Flag == "SideBar")
            {
                UtilityClass.NullSession(UtilityClass.UserSession.OrgDocId, null);
            }

            obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocIdForMadrassa(0);
            return View(obj);
            }
             else
             {
                 return RedirectToAction("Index", "Login");
             }
        }


        // POST: Witness/Create
        [HttpPost]
        public ActionResult CreateMadrassaWitness(MdlWitness obj)
        {
               if (sig != null)
            {
            try
            {
                // TODO: Add insert logic here
                obj.EnterByUser_ID = sig.UserID;
                mobj.AddNewWitness(obj);
                return RedirectToAction("MadrassaWitnessList");

            }
            catch
            {
                obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocIdForMadrassa(0);
                return View(obj);
            }
            }
               else
               {
                   return RedirectToAction("Index", "Login");
               }
        }


        #endregion

        #region NGO/Society



        public ActionResult SocietyWitnessList()
        {
              if (sig != null)
            {
            Lobj = mobj.GetAllWitnessListForSociety();

            return View(Lobj);
            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }
        // GET: Witness/Create
        public ActionResult CreateSocietyWitness(string Flag)
        {
              if (sig != null)
            {
            if (Flag == "SideBar")
            {
                UtilityClass.NullSession(UtilityClass.UserSession.OrgDocId, null);
            }

            obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocIdForSocietyNGO(0);
            return View(obj);
            }
              else
              {
                  return RedirectToAction("Index", "Login");
              }
        }


        // POST: Witness/Create
        [HttpPost]
        public ActionResult CreateSocietyWitness(MdlWitness obj)
        { if (sig != null)
            {
            try
            {
                // TODO: Add insert logic here
                obj.EnterByUser_ID = sig.UserID;
                mobj.AddNewWitness(obj);
                return RedirectToAction("SocietyWitnessList");

            }
            catch
            {
                obj.GetAllOrgDocId = MobjAddress.GetAllOrgDocIdForSocietyNGO(0);
                return View(obj);
            }
            }
        else
        {
            return RedirectToAction("Index", "Login");
        }
        }

        #endregion
    }
}

ProjectFirms01/Views/Addresss/AddressAlter.cshtml
@model BusinessLayer.MdlClasses.MdlADDRESSS
@{
    ViewBag.Title = "AddressAlter";
    Layout = "~/Views/Shared/_FirmLayout.cshtml";
}
@section Header{
    @Html.Partial("~/Views/Shared/PartialViews/_Header.cshtml")
}

@section Sidebar{
    @Html.Partial("~/Views/Shared/PartialViews/_SideBar.cshtml")
}


@section BodyContent{


    @{
        var sig = BusinessLayer.MdlClasses.UtilityClass.GetOrgDocIdSession(BusinessLayer.MdlClasses.UtilityClass.UserSession.OrgDocId);

    }

    <style>
        .form-control {
            /*width: 400px;*/
        }

       .form-horizontal .control-label {
            text-align: left;
            width: 100%;
        }
    </style>

    
    <h2>Old Address Alteration</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="form-horizontal col-sm-5" style="margin-left: 10px;">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })







                @if (sig != null)
                {
                    <div class="form-group">
                        <label style="width:143px;" class="control-label col-md-2">Orgnization Name:</label>
                        <div style="margin: 7px;">
                            <strong class="form-label">@sig.OrgName</strong>
                        </div>
                    </div>
                    <div class="form-group">

                        <label style="margin-left: -44px;" class="control-label col-md-2">File #:</label>
                        <div style="margin: 7px;">
                            <strong class="form-label">@sig.OrgRegNo</strong>
                        </div>
                    </div>

                    <input type="hidden" value="@sig.OrgDocID" name="OrgDoc_ID" id="OrgDoc_ID" />

                    <input type="hidden" value="@sig.OrgDocID" name="OrgDoc_ID" id="OrgDoc_ID" />
                }


                else
                {
                    <div class="form-group">
                        <label class="control-label col-md-2"> Organization/File#</label>
                        <div class="col-md-11">
                            <select class="form-control OrgId" name="OrgId" id="OrgId" style="background:#fff">

                                <option value="0">--Select Organization/File #--</option>

                                @foreach (var item in @Model.GetAllOrgDocId)
                                {
                                    <option selected="@item.Selected" value="@item.Value">@item.Label - @item.OptionalLabel</option>
                                }
                            </select>
                        </div>
                    </div>
                }


                <div class="form-group">
                    <label class="control-label col-md-2"> Address Type</label>
                    <div class="col-md-11">
                        <select class="form-control AdressType_ID" name="AdressType_ID" id="AdressType_ID" style="background:#fff">

                            <option value="0">--Select AddressType--</option>

                            @foreach (var item in @Model.AddressTypes)
                            {
                                <option value="@item.Value">@item.Label</option>
                            }
                        </select>
                    </div>
                </div>





                <div class="form-group">
                    <label class="control-label col-md-2">Select District</label>
                    <div class="col-md-11">
                        <select class="form-control Distric_ID" name="Distric_ID" id="Distric_ID" style="background:#fff">

                            <option value="0">--Select District--</option>

                            @foreach (var item in @Model.DistricsDDL)
                            {
                                <option value="@item.Value">@item.Label</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Select Tehsil</label>
                    <div class="col-md-11">
                        <select class="form-control Tehsil_ID" name="Tehsil_ID" id="Tehsil_ID" style="background:#fff">

                            <option value="0">--Select Tehsil--</option>

                            @*@foreach (var item in @Model.TehsilDDL)
                                {
                                    <option value="@item.Value">@item.Label</option>
                                }*@
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2" >Form B Submission Date</label>

                    <div class="col-md-11">
                        <input type="date" id="FormBSubmissionDate" name="FormBSubmissionDate" class="form-control" />

                        @Html.ValidationMessageFor(model => model.FormBSubmissionDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2" style="width:158px">New Form H Issue No</label>

                    <div class="col-md-11">
                        <input type="text" id="NewFormHIssueNo" name="NewFormHIssueNo" class="form-control" />

                        @Html.ValidationMessageFor(model => model.NewFormHIssueNo, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2" >New Form H Issue Date</label>

                    <div class="col-md-11">
                        <input type="date" id="NewFormHIssueDate" name="NewFormHIssueDate" class="form-control" />

                        @Html.ValidationMessageFor(model => model.NewFormHIssueDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Adress Details</label>

                    <div class="col-md-11">
                        <textarea id="AdressDetails" name="AdressDetails" class="form-control"></textarea>

                        @Html.ValidationMessageFor(model => model.AdressDetails, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-11">
                        <input type="submit" id="AddressAlterbtn" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>

            <div class="col-sm-6" style="margin-top: 62px;">
                <div id="OrgAddressList">


                </div>
            </div>
        </div>

        <input type="hidden" id="TehsilHiddenId" value="@Model.Tehsil_ID" />

        @*<input type="hidden" id="OldAdressId" value="@Model.OldAdressId" name="OldAdressId" />*@

    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>


    <script type="text/javascript">


        //$('#Distric_ID').change(function (e) {
        //    alert("hi");

        //});

        $(document).ready(function () {

            $(".Distric_ID").msDropDown();
            $(".OrgId").msDropDown();
            $(".AdressType_ID").msDropDown();

            //   $('#Distric_ID').trigger('change');


        });

        $('#Distric_ID').change(function () {

            var ID = $(this).val();// $('#Distric_ID option:selected').val();
            var tehsilID = $('#TehsilHiddenId').val();
            $("#Tehsil_ID").empty();
            $("#Tehsil_ID").append("<option value=" + '0' + "> --Select Tehsil-- </option>");
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTehsils", "Addresss")',
                data: { ID: ID, Tehsil: tehsilID },

                success: function (d) {

                    for (i = 0; i < d.length; i++) {
                        var html = "";
                        var id = d[i].Value;
                        var city = d[i].Label;

                        //  console.log(id +''+ city);
                        html += '<option value="' + id + '">' + city + '</option>';
                        $("#Tehsil_ID").append(html);

                    }
                    // $(".Tehsil_ID").msDropDown();
                },
                error: function () {

                }
            });
        });

        GetAddressList();
        function GetAddressList() {
            // alert("HI");
            //  return false;
            var ID
            if ($('#OrgId option:selected').val() == undefined) {
                ID = $.trim($('#OrgId').val());
            }
            else {
                ID = $('#OrgId option:selected').val();
            }
            $.ajax({
                url: '/Addresss/ListOfAddressAlter',
                type: 'GET',
                dataType: "html",
                data: { Id: ID },
                success: function (data) {
                    $("#OrgAddressList").html("").append(data);

                },
                error: function () {
                    // toastr.error(data.message);
                }
            });
        }

        //$('#AssigneeId option:selected').val();
        $('#OrgId').on('change', function () {
            GetAddressList();

        });

    </script>
}

@section FooterArea{
    @Html.Partial("~/Views/Shared/PartialViews/_Footer.cshtml")


}

ProjectFirms01/Views/Addresss/Index.cshtml
@model IEnumerable<BusinessLayer.MdlClasses.MdlADDRESSS>

@{
    ViewBag.Title = "Index";
    
 
    Layout = "~/Views/Shared/_FirmLayout.cshtml";
}


@section Header{
    @Html.Partial("~/Views/Shared/PartialViews/_Header.cshtml")
}

@section Sidebar{
    @Html.Partial("~/Views/Shared/PartialViews/_SideBar.cshtml")
}


@section BodyContent{

<ol class="breadcrumb">
    <li><a href="/Home"><i class="fa fa-dashboard"></i>Home</a></li>
    <li><a href="/Firm">Firm</a></li>
    <li class="active">Address</li>
</ol>
 
<p>
    @Html.ActionLink("Add Address", "Create") /
    @Html.ActionLink("Add Partner", "Create","Partner") /
    @Html.ActionLink("Add Witness", "Create","Witness")
   
    @*@TempData["foo"].ToString();*@
</p>
<table id="example1" class="table table-striped table-responsive table-fixedheader  table-bordered dataTable">
    <thead>
        <tr>

            <th>
                Org Name

            </th>
            <th>
                Address Type
            </th>
            <th>
                Adress Details
            </th>
            <th>
                Tehsil
            </th>
            <th>
                Is Active
            </th>

            <th>
                Enter By
            </th>


            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.OrgName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdressTypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdressDetails)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TehsilName)
                </td>


                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.AdressID })
                    @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }
    </tbody>

</table>

}




@section FooterArea{
    @Html.Partial("~/Views/Shared/PartialViews/_Footer.cshtml")


}